insert into admin ( userName, passWord, level) values('mr','lueSGJZetyySpUndWjMBEg==','4');
insert into admin ( userName, passWord, level) values('admin','lueSGJZetyySpUndWjMBEg==','4');

insert into bbs (Content, postTime) values('在圣诞节来临之际，本书店为答解新老朋友的，特举办购物有奖活动！','2008-12-20 11:00:00');
insert into bbs (Content, postTime) values('购物有奖，快快行动吧！','2009-4-8 15:00:00');

insert into bookClass (className, bookCount) values('Jsp测试','');
insert into bookClass (className, bookCount) values('Visual Basic系列丛书','');
insert into bookClass (className, bookCount) values('Visual FoxPro系列丛书','');
insert into bookClass (className, bookCount) values('PowerBuilder系列丛书','');
insert into bookClass (className, bookCount) values('Delph系列丛书','');
insert into bookClass (className, bookCount) values('PowerBuilder系列丛书','');
insert into bookClass (className, bookCount) values('ASP系列丛书','');
insert into bookClass (className, bookCount) values('Delphi系列丛书','');
insert into bookClass (className, bookCount) values('Visual C＋＋系列丛书','');
insert into bookClass (className, bookCount) values('JSP系列丛书','');


insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, inDatetime ) values('1001-12542051','Jsp测试',1,'Jsp测试','Jsp测试','顶天',34,'','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-12763-3','Visual Basic数据库开发实例解析',2,'机械工业出版社','刘志铭、高春艳、孙健鹏','　软件开发是一项复杂细致的工作，尤其是开发商业管理软件<br/>，不但要求开发人员熟练掌握开发工具的语法知识，而且还要具有商业软件开发的丰富经验。本书以实用商业案例为基础，通过几个完整的商业系统案例，一步一步带领读者完成商业管理软<br/>件开发的各个目标。每个实例都突出实用性，不仅可以了解开发商业管理软件的专业知识，而且可以全面掌握整个商业系统的设计思路和开发技术。全书包含宾馆客房管理系统、钢材综合管<br/>理系统、餐饮管理系统、医药进销存管理系统、珠宝首饰进销存管理系统等五个案例，既有小型Access数据库，也有大型的SQL Server数据库，通过对不同数据库、不同行业的实例开发，<br/>使读者可以快速掌握利用Visual Basic 开发数据库管理软件的精髓。<br/>　　本书附有配套光盘。光盘提供了书中5个案例的全部源代码，全部源代码都经过精心调试，在Windows98下全部通过，保证能够正常运行。<br/>　　本书内容详实，案例完整，步骤详尽，具有很强的实用性。适合于各级软件开发人员学习使用，也可供大中专院校师生学习参考，是编程者不可多得的一本好书。<br/>　　本书的每个案例都可直接作为商业软件使用，在将本书案例直接用于商业行为时，请首先征得作者同意或授权。',48,'','cover\VBsjkkfsljx.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-12812-5','Visual FoxPro数据库开发实例解析',3,'机械工业出版社','王晶莹、王国辉、张雨','软件开发是一项复杂细致的工作，尤其是开发商业管理软件，<br/>不但要求开发人员熟练掌握开发工具的语法知识，而且还要具有商业软件开发的丰富经验。本书以实用商业案例为基础，通过几个完整的商业系统案例，一步一步带领读者完成商业管理软件<br/>开发的各个目标。每个实例都突出实用性，不仅可以了解开发商业管理软件的专业知识，而且可以全面掌握整个商业系统的设计思路和开发技术。全书包含医药管理、物业管理、汽配管理、<br/>客房管理、车辆管理等五个案例，通过对不同行业的实例开发，使读者可以快速掌握利用Visual Foxpro 开发数据库管理软件的精髓。<br/>　　本书附有配套光盘。光盘提供了书中5个案例的全部源代码，全部源代码都经过精心调试，在windows98下全部通过，保证能够正常运行。<br/>　　本书内容详实，案例完整，步骤详尽，具有很强的实用性。适合于各级软件开发人员学习使用，也可供大中专院校师生学习参考。是编程者不可多得的一本好书。<br/>　　本书的每个案例都可直接作为商业软件使用，在将本书案例直接用于商业行为时，请首先征得作者同意或授权。',48,'','cover\vfpsjkkfsljx.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-13024-3','Power Builder数据库开发实例解析',4,'机械工业出版社','华传铭、张振坤、吴晓英','软件开发是一项复杂细致的工作，尤其是开发商业管理软件<br/>，不但要求开发人员熟练掌握开发工具的语法知识，而且还要具有商业软件开发的丰富经验。本书以实用商业案例为基础，通过几个完整的商业系统案例，一步一步带领读者完成商业管理软<br/>件开发的各个目标。每个实例都突出实用性，不仅可以了解开发商业管理软件的专业知识，而且可以全面掌握整个商业系统的设计思路和开发技术。全书包含医药管理、汽配管理、洗浴管理<br/>、客房管理、餐饮管理等五个案例，通过对不同行业的实例开发，使读者可以快速掌握利用Power　Builder 开发数据库管理软件的精髓。<br/>　　本书附有配套光盘。光盘提供了书中5个案例的全部源代码，全部源代码都经过精心调试，在windows98下全部通过，保证能够正常运行。<br/>　　本书内容详实，案例完整，步骤详尽，具有很强的实用性。适合于各级软件开发人员学习使用，也可供大中专院校师生学习参考。是编程者不可多得的一本好书。<br/>　　本书的每个案例都可直接作为商业软件使用，在将本书案例直接用于商业行为时，请首先征得作者同意或授权。',43,'','cover\PBsjkkfsljx.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-13900-3','Delphi数据库开发实例解析',5,'机械工业出版社','赛奎春、郑骁鹏、郑齐心','软件开发是一项复杂细致的工作，尤其是开发商业管理软件，不但要求开发<br/>人员熟练掌握开发工具的语法知识，而且还要具有商业软件开发的丰富经验。本书以实用商业案例为基础，通过几个完整的商业系统案例，一步一步带领读者完成商业管理软件开发的各个目<br/>标。每个实例都突出实用性，不仅可以了解开发商业管理软件的专业知识，而且可以全面掌握整个商业系统的设计思路和开发技术。全书包含餐饮管理系统、物业管理系统、校园管理系统、<br/>维修管理系统、汽配管理系统等五个案例，既有小型Access数据库，也有大型的SQL Server数据库，通过对不同数据库、不同行业的实例开发，使读者可以快速掌握利用Delphi开发数据库<br/>管理软件的精髓。<br/>　　本书附有配套光盘。光盘提供了书中5个案例的全部源代码，全部源代码都经过精心调试，在Windows98/Windows XP下全部通过，保证能够正常运行。<br/>　　本书内容详实，案例完整，步骤详尽，具有很强的实用性。适合于各级软件开发人员学习使用，也可供大中专院校师生学习参考，是编程者不可多得的一本好书。<br/>　　本书的每个案例都可直接作为商业软件使用，在将本书案例直接用于商业行为时，请首先征得作者同意或授权。',49,'','cover\delphisjkkfsljx.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-14939-4','PowerBuilder 精彩编程200例',4,'机械工业出版社','张振坤、李文立、集虹等','本书通过大量实例，分门别类地对PowerBuilder的编程方法进<br/>行了全页深入的介绍。全书分为窗体、控件、类与菜单，数据库技术，多媒体与图形，文件与系统，网络与Internet五个部分，共200个实例。每个实例都突出实用性，其中大部分是程序开<br/>发者常见问题的解决方案。本书的配套光盘，提供了书中200个案例的全部源代码，这些源代码都已经过调试，并在windows98下全部通过。<br/>　　本书适用于广大计算机爱好者和编程人员学习开发使用，也可供大中专院校师生学习参考。可以满足不同消费者的需要。是编程者不可多得的一本好书。',39,'','cover\PB200l.jpg','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-14967-X','Visual FoxPro 精彩编程200例',3,'机械工业出版社','王国辉、董韶华、韩旭等','本书通过大量实例，详细介绍了Visual FoxPro编程的经验与技<br/>巧。全书分为界面、控件、类与表单，数据库技术，多媒体与图形，文件与系统，网络与Internet五个部分，共200个实例。每个实例都突出实用性，其中大部分是程序开发者常见问题的解<br/>决方案。本书的配套光盘，提供了书中200个案例的全部源代码，所有源代码都经过精心调试，在windows98下全部通过，保证能够正常运行。<br/>　　本书适用于广大计算机爱好者和编程人员学习开发使用，也可供大中专院校师生学习参考。可以满足不同消费者的需要。是编程者不可多得的一本好书。',39,'','cover\VFP200l.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-15531-9','ASP数据库开发实例解析',7,'机械工业出版社','李严、于亚芳、王国辉','本书以实用网络应用程序开发实例为基础，通过几个完整的商业实例，一步一步带<br/>领读者完成网络应用程序开发的各个目标。书中的每个实例都突出实用性，通过学习，读者不仅可以了解开发商业网络系统的专业知识，而且可以全面掌握整个网络系统的设计思路。书中包<br/>含：网上图书管理系统、网上商品交易系统、网上客户管理系统、网上企业办公自动化系统、企业网上交流平台等五个实例。所使用的数据库即有小型Access数据库，也有大型SQL Server<br/>数据库。通过对不同数据库、不同行业的实例开发，可使读者快速掌握利用ASP开发数据库管理软件的精髓。<br/>    本书内容详实，实例完整，步骤清晰，具有很强的实用性。适合各级网络开发人员学习使用，也可供大中专院校师生学习参考，是网络编程者不可多得的一本好书。',36,'','cover\ASPsjkkfsljx.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-15821-0','Delphi工程应用与项目实践',8,'机械工业出版社','宋坤 赵智勇等','　本书从项目开发必备的知识和原则入手，全面系统地介绍了Delphi在工程开发中的<br/>编程知识、方法和技巧。全书在前10章节主要介绍Delphi程序设计的重点和难点技术，每章首先进行知识讲解，然后结合相关知识在工程开发中的应用实例深化理解，应用实例注重实用性<br/>、启发性，使读者能结合所学知识快速掌握ASP程序的开发方法和技巧。第11章、第12章主要以两个工程实例系统介绍项目开发的完整过程，使读者在掌握Delphi程序开发的精髓。<br/>　　全书注重所讲知识的工程应用。作者从多-开发工程项目的实践入手，将编程必备的知识与工程开发中的实际案例相结合，使读者在掌握Delphi软件的同时，快速掌握相关编程知识在工<br/>作实践中的使用方法和技巧，分享作者的开发经验。',39,'','cover\Delphigcyyysj.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-15860-1','Visual Basic工程应用与项目实践',2,'机械工业出版社','高春艳、李俊民等','本书从项目开发必备的知识和原则入手，全面系统地介绍了Visual <br/>Basic在工程开发中的编程知识、方法和技巧。全书在前12章主要介绍Visual Basic进行程序设计的重点和难点技术，每章首先进行知识讲解，然后结合相关知识在工程开发中的应用实例深<br/>化理解，应用实例注重实用性、启发性，使读者能结合所学知识快速掌握Visual Basic程序的开发方法和技巧。后两章通过物业和酒店管理系统两个完整实例循序渐进地介绍Visual Basic项<br/>目开发的完整过程，使读者在掌握Visual Basic基本开发方法和技巧后，能够快速掌握实用项目的开发思路和方法。从而领会Visual Basic的精髓。<br/>　　全书注重所讲知识的工程应用。作者从多-的开发工程项目的实践入手，将编程必备的知识与工程开发中的实际案例相结合，使读者在学习Visual Basic的同时，快速分享作者在开发中<br/>的经验。全书按照深入浅出的原则，根据不同的开发知识和不同的工程应用问题进行了详细的讲解。<br/>　　本书中的实例多来源于我们开发的实际项目，这些例子都具有实际应用的价值，为使读者能更好的使用本书，随书光盘包含了所有实例的源代码程序。',43,'','cover\VBgcyyysj.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-15960-8','Visual C＋＋工程应用与项目实践',9,'机械工业出版社','张雨、阮伟良、李贺等','本书从项目开发必备的知识和原则入手，全面系统地介绍了MFC<br/>在工程开发中的编程知识、方法和技巧。全书前9章主要介绍MFC程序设计的重点和难点技术。每章首先进行知识讲解，然后结合相关知识在工程开发中的应用实例深化理解应用，实例注重<br/>实用性、启发性和典型性，使读者能结合所学知识快速掌握Visual C++程序的开发方法和技巧。第10章通过一个完整工程实例的开发过程，带领读者快掌握实用项目的开发思路和方法，从<br/>而领会MFC程序开发的精髓。<br/>　　全书分为10章，包括MFC编程基础、文件与文件系统在程序开发中的应用、图形与多媒体技术在开发中的应用、注册表、操作系统编程、输入输出技术、Visual C++高级应用、数据库<br/>程序设计、网络与INTERNET程序设计、物流综合管理系统。<br/>　　全书注重所讲知识的工程应用。作者从多-开发工程项目的实践入手，将编程必备的知识与工程开发中的实际案例相结合，使读者在学习Visual C++的同时，快速分享作者在开发中的<br/>开发经验。全书按照深入浅出的原则，根据不同的开发知识和不同的工程应用问题进行了详细讲解。',41,'','cover\VCgcyyysj.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-15984-5','JSP工程应用与项目实践',10,'机械工业出版社','陈威、白伟明、李楠','本书从项目开发必备的知识和原则入手，全面系统地介绍了JSP在工程开发中的编程知<br/>识、方法和技巧。全书在前9章中主要介绍JSP开发Web应用程序的重点和难点技术，每章首先进行知识讲解，然后结合相关知识在工程开发中的应用实例深化理解，应用实例注重实用性、<br/>启发性，使读者能结合所学知识快速掌握JSP程序的开发方法和技巧。后3章通过社区、网上书店和办公自动化系统3个完整实例循序渐进地介绍JSP项目开发的完整过程，使读者在掌握JSP基<br/>本开发方法和技巧后，能够快掌握实用项目的开发思路和方法，从而领会JSP的精髓。<br/>　　全书注重所讲知识的工程应用。作者从多-开发工程项目的实践入手，将编程必备的知识与工程开发中的实际案例相结合，使读者在学习JSP的同时，快速分享作者的开发经验。全书按<br/>照深入浅出的原则，根据不同的开发知识和不同的工程应用问题进行了详细讲解。<br/>　　本书中的实例多来源于我们开发的实际项目，这些例子都具有实际应用的价值，为使读者能更好的使用本书，随书光盘包含了所有实例的源代码程序。',38,'','cover\JSPgcyyysj.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-16332-X','ASP工程应用与项目实践',7,'机械工业出版社','王国辉、牛强、李南南','　本书从项目开发必备的知识和原则入手，全面系统地介绍了ASP在工程开发中的<br/>编程知识、方法和技巧。全书在前10章主要介绍ASP在开发Web应用程序的重点和难点技术，每章首先进行知识讲解，然后结合相关知识在工程开发中的应用实例深化理解，应用实例注重<br/>实用性、启发性，使读者能结合所学知识快速掌握ASP程序的开发方法和技巧。后两章通过网上教学系统和网上商城两个完整实例循序渐进地介绍ASP项目开发的完整过程，使读者在掌握<br/>ASP基本开发方法和技巧后，能够快掌握实用项目的开发思路和方法，从而领会ASP的精髓。<br/>　　全书注重所讲知识的工程应用。作者从多-开发工程项目的实践入手，将编程必备的知识与工程开发中的实际案例相结合，使读者在学习ASP的同时，快速分享作者的开发经验。全书按<br/>照深入浅出的原则，根据不同的开发知识和不同的工程应用问题进行了详细讲解。<br/>　　本书中的实例多来源于我们开发的实际项目，这些例子都具有实际应用的价值，为使读者能更好的使用本书，随书光盘包含了所有实例的源代码程序。',42,'','cover\ASPgcyyysj.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-16490-4','Visual Basic 信息系统开发实例精选',2,'机械工业出版社','高春艳、李俊民、张耀庭等','暂无',44,'','cover\VBxxxtkfsljx.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-16617-5','ASP 信息系统开发实例精选',7,'机械工业出版社','王国辉、牛强、李南南等','暂无',45,'','cover\ASPxxxtkfsljx.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-16761-9','Delphi 信息系统开发实例精选',8,'机械工业出版社','宋坤、赵智勇、刘强等','暂无',44,'','cover\Delphixxxtkfsljx.jpg','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-111-17275-2','JSP信息系统开发实例精选',10,'机械工业出版社','白伟明、赵玉君、李南南','本书精选了大学生就业求职网、物流信息平台、华奥汽车销售集团网站、佳美网<br/>络购物中心、科研成果申报管理系统、安瑞奥国际商务学院招生网、明日宽带影院、雄霸天下游戏网等8个综合的网络信息系统工程作为案例，深入剖析了实际的网络信息系统的开发思路、<br/>方法和技巧。帮助读者透彻掌握了JSP开发网络信息系统的方法和步骤，从而设计出具有实用价值和商业价值的信息系统。',44,'','cover\JSPxxxtkfsljx.gif','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-115-12092-7','Visual foxpro数据库开发关键技术与实例应用',3,'人民邮电出版社','周桓、张雨、王国辉等','本书从Visual FoxPro用户经常遇到的问题入手，<br/>结合应用实例的讲解，帮助读者快速掌握使用Visual FoxPro开发数据库管理系统的关键技术、方法和技巧，从而开发出适合企业应用的数据库系统。<br/>   全书共分为13章，内容包括如何使用代码设计SQL Server数据库、如何连接数据库、数据集与数据访问组件应用技巧、数据输入输出技术、常用控制组件应用技术、SQL数据查询技术、<br/>设计报表和图表、软件与数据库安全、计算机外围硬件程序设计、数据库典型程序设计、多层结构程序开发设计、SQL Server 2000开发设计、使用InstallShield制作安装程序。<br/>   本书配套光盘中提供了书中应用实例的源程序代码，所有源程序均在Windows 98或Windows XP下调试通过，确保能够正常运行。本书内容精练、重点突出，适合Delphi程序开发人员阅<br/>读和参考，也可供大中专院校计算机相关专业的师生学习。',40,'','cover\delphisjkkfgjjsyslyy.jpg','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-115-12094-X','PoweBuilder数据库开发关键技术与实例应用',4,'人民邮电出版社','刘志铭 张振坤 冯文萃','本书从Visual FoxPro用户开发数据库管理系统时遇到<br/>的问题入手，介绍了用Visual FoxPro开发数据库管理系统的关键技术与技巧。全书共分为13章，包括如何设计数据库、表和索引，如何在数据库中设计视图，如何对表单进行基本操作，常<br/>用的数据输入技巧，如何设计报表和标签，控件的开发技巧，程序主窗体、菜单、工具栏的设计，典型表单的设计，怎样访问其他数据库，如何在Visual FoxPro中使用Win32API，硬件接口<br/>程序设计、系统发布与运行等。书中配光盘中提供了所有案例的全部源代码，所有源代码均在Windwos 98下调试通过，确保能够正常运行。',36,'','cover\pbsjkkfgjjsyslyy.jpg','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-115-12096-X','Delphi数据库开发关键技术与实例应用',8,'人民邮电出版社','赛奎春 陈紫鸿 宋昆','本书从Delphi用户经常遇到的问题入手，结合应用实例的讲解，帮助<br/>读者快速掌握使用Delphi开发数据库管理系统的关键技术、方法和技巧，从而开发出适合企业应用的数据库系统。<br/>   全书共分为13章，内容包括如何使用代码设计SQL Server数据库、如何连接数据库、数据集与数据访问组件应用技巧、数据输入输出技术、常用控制组件应用技术、SQL数据查询技术、<br/>设计报表和图表、软件与数据库安全、计算机外围硬件程序设计、数据库典型程序设计、多层结构程序开发设计、SQL Server 2000开发设计、使用InstallShield制作安装程序。<br/>   本书配套光盘中提供了书中应用实例的源程序代码，所有源程序均在Windows 98或Windows XP下调试通过，确保能够正常运行。本书内容精练、重点突出，适合Delphi程序开发人员阅<br/>读和参考，也可供大中专院校计算机相关专业的师生学习。',40,'','cover\delphisjkkfgjjsyslyy.jpg','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-115-12098-6','Visual basic数据库开发关键技术与实例应用',2,'人民邮电出版社','高春艳、李艳','本书从Visual Basic用户经常遇到的问题入手，结合应用实例的<br/>讲解，帮助读者快速掌握使用Delphi开发数据库管理系统的关键技术、方法和技巧，从而开发出适合企业应用的数据库系统。<br/>   全书共分为13章，内容包括如何使用代码设计SQL Server数据库、如何连接数据库、数据集与数据访问组件应用技巧、数据输入输出技术、常用控制组件应用技术、SQL数据查询技术、<br/>设计报表和图表、软件与数据库安全、计算机外围硬件程序设计、数据库典型程序设计、多层结构程序开发设计、SQL Server 2000开发设计、使用InstallShield制作安装程序。<br/>   本书配套光盘中提供了书中应用实例的源程序代码，所有源程序均在Windows 98或Windows XP下调试通过，确保能够正常运行。本书内容精练、重点突出，适合Delphi程序开发人员阅<br/>读和参考，也可供大中专院校计算机相关专业的师生学习。',40,'','cover\Vbsjkkfgjjsyslyy.jpg','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-115-13702-1','Visual C＋＋ 管理信息系统完整项目实例剖析',9,'人民邮电出版社','明日科技','暂无',48,'','cover\VCglxxxtwzxmslpx.jpg','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-115-13703-X','Visual Basic 管理信息系统完整项目实例剖析',2,'人民邮电出版社','明日科技','暂无',40,'','cover\VBglxxxtwzxmslpx.jpg','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-115-13704-8','PowerBuilder 管理信息系统完整项目实例剖析',4,'人民邮电出版社','明日科技','暂无',44,'','cover\PBglxxxtwzxmslpx.jpg','');
insert into bookInfo (ISBN, bookName, classID, publisher, author, introduce, price, pubDatetime, coverPath, inDatetime ) values('7-115-13705-6','Visual FoxPro管理信息系统完整项目实例剖析',3,'人民邮电出版社','明日科技','暂无',46,'','cover\Visual FoxProglxxxtwzxmslpx.jpg','');


insert into users ( userName, trueName, passWord, address, postcode, grade, tel, email, freeze) values('无语','吴语','111111','长春市朝阳区','130061','0','13614448007','wgh@sina.com','0');
insert into users ( userName, trueName, passWord, address, postcode, grade, tel, email, freeze) values('blueStar','BLUE星梦','000000','长春市二道区','130031','0','13614449169','bluestar@sohu.com','0');
insert into users ( userName, trueName, passWord, address, postcode, grade, tel, email, freeze) values('wind','封轻杨','000000','长春市二道区','130031','0','4972266','fqy777@sina.com','0');
insert into users ( userName, trueName, passWord, address, postcode, grade, tel, email, freeze) values('wgh','王国辉','111','长春市朝阳区','136000','1','3642159','iceer@sohu.com','0');
insert into users ( userName, trueName, passWord, address, postcode, grade, tel, email, freeze) values('icer','冰','111111','长春市','130031','0','13622445544755','icer@sohu.com','0');
insert into users ( userName, trueName, passWord, address, postcode, grade, tel, email, freeze) values('sxp','孙蓝','111111','东盛大街','130051','0','13844817613','sunxiaopeng666@163.com','1');
insert into users ( userName, trueName, passWord, address, postcode, grade, tel, email, freeze) values('gyl','顾问','111111','','','0','','yangjun1@sina.com','0');



insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('5','任逍遥','四平市铁西区','136000','3642159','iceer@sohu.com','普通邮寄','2005-12-12 16:48:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('5','任逍遥','四平市铁西区','136000','3642159','iceer@sohu.com','普通邮寄','2005-12-12 16:50:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('5','任逍遥','四平市铁西区','136000','3642159','iceer@sohu.com','普通邮寄','2005-12-12 16:53:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('6','孙蓝','东盛大街','130051','13844817613','sunxiaopeng666@163.com','普通邮寄','2005-12-16 08:58:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('6','孙蓝','东盛大街','130051','13844817613','sunxiaopeng666@163.com','普通邮寄','2005-12-16 09:02:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('6','孙蓝','东盛大街','130051','13844817613','sunxiaopeng666@163.com','普通邮寄','2005-12-16 09:05:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('6','孙蓝','东盛大街','130051','13844817613','sunxiaopeng666@163.com','普通邮寄','2005-12-16 09:07:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('6','孙蓝','东盛大街','130051','13844817613','sunxiaopeng666@163.com','普通邮寄','2005-12-16 09:09:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('4','王国辉','长春市朝阳区','136000','3642159','iceer@sohu.com','普通邮寄','2005-12-19 09:11:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('4','王国辉','长春市朝阳区','136000','3642159','iceer@sohu.com','普通邮寄','2005-12-22 10:13:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('4','王国辉','长春市朝阳区','136000','3642159','iceer@sohu.com','普通邮寄','2005-12-31 10:01:00','');
insert into orders (userID, trueName, address, postcode, tel, email,dealMethod, orderDatetime, pay) values('4','王国辉','长春市朝阳区','136000','3642159','iceer@sohu.com','普通邮寄','2006-01-11 15:20:00','');



insert into orderDetail (orderID, bookID, price, number) values(1,2,48,1);
insert into orderDetail (orderID, bookID, price, number) values(2,2,48,1);
insert into orderDetail (orderID, bookID, price, number) values(2,18,38,1);
insert into orderDetail (orderID, bookID, price, number) values(3,2,48,1);
insert into orderDetail (orderID, bookID, price, number) values(4,13,42,1);
insert into orderDetail (orderID, bookID, price, number) values(5,13,42,1);
insert into orderDetail (orderID, bookID, price, number) values(6,12,38,2);
insert into orderDetail (orderID, bookID, price, number) values(6,13,42,1);
insert into orderDetail (orderID, bookID, price, number) values(7,12,38,5);
insert into orderDetail (orderID, bookID, price, number) values(8,12,36.1,1);


insert into poll (theme, available) values('热销书分类投票', 1);


insert into pollDetail ( pollID, optionName, counts) values(1,'实例类','5');
insert into pollDetail ( pollID, optionName, counts) values(1,'教程类','3');
insert into pollDetail ( pollID, optionName, counts) values(1,'手册类','3');
insert into pollDetail ( pollID, optionName, counts) values(1,'经验技巧类','2');

